name: CI

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: ${{ matrix.os }}-latest
    strategy:
      matrix:
        os: [ubuntu, windows]
        include:
          - os: windows
            shell: msys2
          - os: ubuntu
            shell: bash
    defaults:
      run:
        shell: ${{ matrix.shell }} {0}
    steps:
      - uses: actions/checkout@v2
      - name: Install Ubuntu dependencies
        if: matrix.os == 'ubuntu'
        run: |
          sudo add-apt-repository -y ppa:alex-p/deadbeef
          sudo apt-get -qq update
          sudo apt-get -qq install deadbeef-dev build-essential pkg-config libgtk2.0-dev libgtk-3-dev
      - name: Install Windows dependencies
        if: matrix.os == 'windows'
        uses: msys2/setup-msys2@v2
        with:
          update: true
          install: >-
            mingw-w64-x86_64-toolchain make
            mingw-w64-x86_64-pkg-config mingw-w64-x86_64-gtk2 mingw-w64-x86_64-gtk3
      - name: Build
        run: |
          make
          make GTK=2
      - name: Install
        run: |
          make install DESTDIR=../release PREFIX="" RPATH='\$$ORIGIN/lib'
          make install DESTDIR=../release PREFIX="" RPATH='\$$ORIGIN/lib' GTK=2
      - name: Upload installed build
        uses: actions/upload-artifact@master
        with:
          name: release
          path: release/
          if-no-files-found: error

  publish:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/master'
    steps:
      - name: Fetch release
        uses: actions/download-artifact@master
        with:
          name: release
          path: release/
      - name: Define release
        id: define_release
        run: |
          echo "::set-output name=TAG::v$(date +'%Y%m%d.%H%M%S')"
          echo "::set-output name=NAME::deadbeef_dr_meter_${RUNNER_OS}_$(echo $GITHUB_SHA | cut -c1-7).tar.gz"
      - name: Pack release
        run: |
          cd release
          tar cf ../${{ steps.define_release.outputs.NAME }} *
      - name: Publish release
        uses: ncipollo/release-action@v1
        with:
          artifacts: ${{ steps.define_release.outputs.NAME }}
          commit: ${{ github.sha }}
          tag: ${{ steps.define_release.outputs.TAG }}
          token: ${{ secrets.GITHUB_TOKEN }}
          artifactErrorsFailBuild: true
